import { oid, model } from './base.js';
export const CashClosing = model('CashClosing', {
  branchId: { ...oid, ref: 'Branch', required: true },
  date: { type: String, required: true },
  cutoffAt: { type: Date, required: true },
  expectedAmount: { type: Number, required: true },
  countedAmount: { type: Number, required: true },
  difference: { type: Number, required: true },
  paymentsCount: Number,
  refundsCount: Number,
  closedBy: { ...oid, ref: 'User' },
  openingAmount: { type: Number, default: 0 },
  expensesAmount: { type: Number, default: 0 },
  transfersInAmount: { type: Number, default: 0 },
  transfersOutAmount: { type: Number, default: 0 },
  varianceExplanation: { type: String, default: '' },
  auditRef: { type: String, unique: true, required: true },
  approvedBy: { ...oid, ref: 'User' },
  approvedAt: Date,
  approvalAuditRef: String,
  handoverTo: { ...oid, ref: 'User' },
  handoverAt: Date,
  handoverNote: String,
  handoverAuditRef: String,
}, [[{ branchId: 1, date: 1 }, { unique: true }]]);
