import React, { useCallback, useState } from 'react';
import { Alert } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { api } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { Page, Card, Title, Muted, Field, Button, Choice, ErrorText, Empty, Busy } from '../components/UI';
const money = amount => `PKR ${(Number(amount || 0) / 100).toLocaleString()}`;
export default function BankReconciliationScreen() {
  const { user } = useAuth();
  const [branches, setBranches] = useState([]), [items, setItems] = useState([]), [branchId, setBranchId] = useState('');
  const [rowKey, setRowKey] = useState(''), [bankReference, setBankReference] = useState(''), [amount, setAmount] = useState(''), [transactionDate, setTransactionDate] = useState(new Date().toISOString().slice(0, 10)), [description, setDescription] = useState('');
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async () => { try { const [b, r] = await Promise.all([api('/branches'), api('/bank-reconciliation')]); setBranches(b.items); setItems(r.items); setBranchId(previous => previous || b.items[0]?._id || ''); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const importRow = async () => { const paisa = Math.round(Number(amount) * 100); if (!branchId || !rowKey.trim() || !bankReference.trim() || !Number.isSafeInteger(paisa) || paisa < 1 || !/^\d{4}-\d{2}-\d{2}$/.test(transactionDate)) return setError('Enter branch, unique row key, bank reference, amount and YYYY-MM-DD date'); try { setBusy(true); const r = await api('/bank-reconciliation/import', 'POST', { branchId, rows: [{ rowKey: rowKey.trim(), bankReference: bankReference.trim(), amount: paisa, transactionDate, description }] }); Alert.alert('Imported', `${r.matched ? 'Matched' : 'Unmatched'} statement row. Import is not payment verification.`); setRowKey(''); setBankReference(''); setAmount(''); setDescription(''); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const review = (item, decision) => Alert.prompt('Review reconciliation', decision === 'APPROVE_MATCH' ? 'Optional note' : 'Required discrepancy reason', async note => { if (decision !== 'APPROVE_MATCH' && !String(note || '').trim()) return setError('A discrepancy reason is required'); try { setBusy(true); await api(`/bank-reconciliation/${item._id}/review`, 'POST', { decision, discrepancyReason: String(note || '') }); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }, 'plain-text', '', 'Submit');
  const canImport = ['SUPER_ADMIN', 'ACCOUNTANT'].includes(user.role), canReview = ['SUPER_ADMIN', 'PRINCIPAL'].includes(user.role);
  return <Page><Title>Bank reconciliation</Title><Muted>Statement imports are evidence for matching only; they never verify or mutate a payment.</Muted><ErrorText message={error} />{loading ? <Busy /> : <>{canImport && <Card><Title>Import statement row</Title><Choice label="Branch" value={branchId} onChange={setBranchId} options={branches.map(b => ({ value: b._id, label: b.name }))} /><Field label="Unique statement row key" value={rowKey} onChangeText={setRowKey} /><Field label="Bank reference" value={bankReference} onChangeText={setBankReference} /><Field label="Amount (PKR)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /><Field label="Transaction date (YYYY-MM-DD)" value={transactionDate} onChangeText={setTransactionDate} /><Field label="Description" value={description} onChangeText={setDescription} /><Button title="Import and match" onPress={importRow} busy={busy} /></Card>}<Title>Review queue</Title>{items.length ? items.map(item => <Card key={item._id}><Title>{item.status} · {money(item.amount)}</Title><Muted>{item.branchId?.name || 'Branch'} · {item.bankReference} · {item.transactionDate}{'\n'}{item.matchReason || item.discrepancyReason || 'Awaiting review'}{'\n'}Audit: {item.auditRef}{item.reviewAuditRef ? `\nReview audit: ${item.reviewAuditRef}` : ''}</Muted>{canReview && !item.reviewedAt && item.status === 'MATCHED' && <Button title="Approve matched receipt" secondary onPress={() => review(item, 'APPROVE_MATCH')} busy={busy} />}{canReview && !item.reviewedAt && item.status === 'UNMATCHED' && <><Button title="Accept as unmatched" secondary onPress={() => review(item, 'ACCEPT_UNMATCHED')} busy={busy} /><Button title="Reject row" secondary onPress={() => review(item, 'REJECT')} busy={busy} /></>}</Card>) : <Empty text="No bank statement rows imported." />}<Button title="Refresh" secondary onPress={load} busy={loading} /></>}</Page>;
}
